#!/bin/bash

# Repository Baseline Script for Ubuntu/Linux Mint
# Provides safe baseline configurations for sources.list
# Must be run as root

if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root (use sudo)"
    exit 1
fi

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================"
echo "  REPOSITORY BASELINE TOOL"
echo "========================================${NC}"
echo ""

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    VERSION=$VERSION_ID
    CODENAME=$VERSION_CODENAME
    
    # For Linux Mint, also get Ubuntu base
    if [ "$ID" = "linuxmint" ]; then
        UBUNTU_CODENAME=$(grep "UBUNTU_CODENAME" /etc/os-release | cut -d= -f2)
    fi
else
    echo -e "${RED}Error: Cannot detect OS version${NC}"
    exit 1
fi

echo -e "${BLUE}Detected System:${NC}"
echo "  OS: $OS"
echo "  Version: $VERSION"
echo "  Codename: $CODENAME"
if [ -n "$UBUNTU_CODENAME" ]; then
    echo "  Ubuntu Base: $UBUNTU_CODENAME"
fi
echo ""

# Function to backup current configuration
backup_current() {
    BACKUP_DIR="/root/repo_backup_$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    
    echo -e "${BLUE}[*]${NC} Creating backup of current configuration..."
    echo "    Backup directory: $BACKUP_DIR"
    
    # Backup sources.list
    if [ -f /etc/apt/sources.list ]; then
        cp /etc/apt/sources.list "$BACKUP_DIR/"
        echo "    ✓ Backed up /etc/apt/sources.list"
    fi
    
    # Backup sources.list.d
    if [ -d /etc/apt/sources.list.d ]; then
        cp -r /etc/apt/sources.list.d "$BACKUP_DIR/"
        echo "    ✓ Backed up /etc/apt/sources.list.d/"
    fi
    
    # Backup trusted.gpg.d
    if [ -d /etc/apt/trusted.gpg.d ]; then
        cp -r /etc/apt/trusted.gpg.d "$BACKUP_DIR/"
        echo "    ✓ Backed up /etc/apt/trusted.gpg.d/"
    fi
    
    # Backup keyrings
    if [ -d /usr/share/keyrings ]; then
        mkdir -p "$BACKUP_DIR/usr_share_keyrings"
        cp /usr/share/keyrings/*.gpg "$BACKUP_DIR/usr_share_keyrings/" 2>/dev/null
        echo "    ✓ Backed up /usr/share/keyrings/"
    fi
    
    echo -e "${GREEN}    Backup complete!${NC}"
    echo ""
}

# Function to show current repositories
show_current_repos() {
    echo -e "${BLUE}[*] Current Repository Configuration:${NC}"
    echo "----------------------------------------"
    
    echo ""
    echo "Main sources.list:"
    if [ -f /etc/apt/sources.list ]; then
        grep -v "^#" /etc/apt/sources.list | grep -v "^$" | sed 's/^/  /'
    else
        echo "  (file not found)"
    fi
    
    echo ""
    echo "Additional repositories in sources.list.d/:"
    if [ -d /etc/apt/sources.list.d ]; then
        for file in /etc/apt/sources.list.d/*.list; do
            if [ -f "$file" ]; then
                echo "  File: $(basename $file)"
                grep -v "^#" "$file" | grep -v "^$" | sed 's/^/    /'
            fi
        done
    fi
    
    echo ""
    echo "Trusted GPG keys:"
    if [ -d /etc/apt/trusted.gpg.d ]; then
        ls -1 /etc/apt/trusted.gpg.d/ | sed 's/^/  /'
    fi
    
    echo ""
}

# Function to generate safe baseline for Ubuntu
generate_ubuntu_baseline() {
    local codename=$1
    local mirror="http://archive.ubuntu.com/ubuntu"
    
    # Use local mirror if available (faster)
    if [ -f /etc/apt/sources.list ]; then
        current_mirror=$(grep -m1 "^deb " /etc/apt/sources.list | awk '{print $2}')
        if [[ "$current_mirror" =~ ^http://[a-z]{2}\.archive\.ubuntu\.com ]]; then
            mirror="$current_mirror"
        fi
    fi
    
    cat > /etc/apt/sources.list << EOF
# Ubuntu Official Repositories - $codename
# Generated by Repository Baseline Tool on $(date)

# Main repositories
deb $mirror $codename main restricted universe multiverse
deb $mirror $codename-updates main restricted universe multiverse
deb $mirror $codename-backports main restricted universe multiverse

# Security updates
deb http://security.ubuntu.com/ubuntu $codename-security main restricted universe multiverse

# Source repositories (uncomment if needed)
# deb-src $mirror $codename main restricted universe multiverse
# deb-src $mirror $codename-updates main restricted universe multiverse
# deb-src http://security.ubuntu.com/ubuntu $codename-security main restricted universe multiverse
EOF

    echo -e "${GREEN}✓ Generated safe baseline for Ubuntu $codename${NC}"
}

# Function to generate safe baseline for Linux Mint
generate_mint_baseline() {
    local mint_codename=$1
    local ubuntu_codename=$2
    local mint_mirror="http://packages.linuxmint.com"
    local ubuntu_mirror="http://archive.ubuntu.com/ubuntu"
    
    cat > /etc/apt/sources.list << EOF
# Linux Mint Official Repositories - $mint_codename
# Generated by Repository Baseline Tool on $(date)

# Linux Mint repositories
deb $mint_mirror $mint_codename main upstream import backport

# Ubuntu base repositories
deb $ubuntu_mirror $ubuntu_codename main restricted universe multiverse
deb $ubuntu_mirror $ubuntu_codename-updates main restricted universe multiverse
deb $ubuntu_mirror $ubuntu_codename-backports main restricted universe multiverse

# Ubuntu security updates
deb http://security.ubuntu.com/ubuntu $ubuntu_codename-security main restricted universe multiverse

# Source repositories (uncomment if needed)
# deb-src $mint_mirror $mint_codename main upstream import backport
# deb-src $ubuntu_mirror $ubuntu_codename main restricted universe multiverse
EOF

    echo -e "${GREEN}✓ Generated safe baseline for Linux Mint $mint_codename${NC}"
}

# Function to clean suspicious repositories
clean_suspicious_repos() {
    echo -e "${BLUE}[*] Checking for suspicious repositories...${NC}"
    echo ""
    
    suspicious_found=0
    
    # Check sources.list.d for potentially unwanted repositories
    if [ -d /etc/apt/sources.list.d ]; then
        for file in /etc/apt/sources.list.d/*.list; do
            if [ -f "$file" ]; then
                # Check for common suspicious patterns
                if grep -qiE 'ppa.*getdeb|ppa.*webupd8|unsigned|insecure' "$file"; then
                    echo -e "${YELLOW}[!] Potentially suspicious: $(basename $file)${NC}"
                    grep -v "^#" "$file" | grep -v "^$" | sed 's/^/    /'
                    suspicious_found=1
                fi
            fi
        done
    fi
    
    if [ $suspicious_found -eq 0 ]; then
        echo -e "${GREEN}✓ No obviously suspicious repositories found${NC}"
    else
        echo ""
        echo -n "Do you want to move suspicious .list files to backup? [y/N]: "
        read -r response
        if [[ "$response" =~ ^[Yy]$ ]]; then
            mkdir -p "$BACKUP_DIR/suspicious_repos"
            for file in /etc/apt/sources.list.d/*.list; do
                if [ -f "$file" ] && grep -qiE 'ppa.*getdeb|ppa.*webupd8|unsigned|insecure' "$file"; then
                    mv "$file" "$BACKUP_DIR/suspicious_repos/"
                    echo -e "${GREEN}✓ Moved $(basename $file) to backup${NC}"
                fi
            done
        fi
    fi
    echo ""
}

# Main menu
show_current_repos

echo ""
echo "What would you like to do?"
echo "  1) Create backup of current configuration"
echo "  2) Reset to safe baseline (Ubuntu)"
echo "  3) Reset to safe baseline (Linux Mint)"
echo "  4) Clean suspicious repositories"
echo "  5) Show recommended GPG key setup"
echo "  6) Exit"
echo ""
echo -n "Enter choice [1-6]: "
read -r choice

case $choice in
    1)
        backup_current
        ;;
    2)
        if [[ "$ID" != "ubuntu" ]]; then
            echo -e "${YELLOW}Warning: This doesn't appear to be Ubuntu${NC}"
            echo -n "Continue anyway? [y/N]: "
            read -r response
            if [[ ! "$response" =~ ^[Yy]$ ]]; then
                exit 0
            fi
        fi
        
        echo ""
        backup_current
        generate_ubuntu_baseline "$CODENAME"
        
        echo ""
        echo -e "${BLUE}[*] Cleaning sources.list.d...${NC}"
        echo -n "Remove all files in sources.list.d? [y/N]: "
        read -r response
        if [[ "$response" =~ ^[Yy]$ ]]; then
            rm -f /etc/apt/sources.list.d/*.list
            echo -e "${GREEN}✓ Cleaned sources.list.d${NC}"
        fi
        
        echo ""
        echo -e "${BLUE}[*] Updating package lists...${NC}"
        apt update
        echo ""
        echo -e "${GREEN}✓ Repository baseline applied!${NC}"
        ;;
    3)
        if [[ "$ID" != "linuxmint" ]]; then
            echo -e "${YELLOW}Warning: This doesn't appear to be Linux Mint${NC}"
            echo -n "Continue anyway? [y/N]: "
            read -r response
            if [[ ! "$response" =~ ^[Yy]$ ]]; then
                exit 0
            fi
        fi
        
        if [ -z "$UBUNTU_CODENAME" ]; then
            echo -e "${RED}Error: Cannot determine Ubuntu base codename${NC}"
            exit 1
        fi
        
        echo ""
        backup_current
        generate_mint_baseline "$CODENAME" "$UBUNTU_CODENAME"
        
        echo ""
        echo -e "${BLUE}[*] Cleaning sources.list.d...${NC}"
        echo -n "Remove all files in sources.list.d? [y/N]: "
        read -r response
        if [[ "$response" =~ ^[Yy]$ ]]; then
            rm -f /etc/apt/sources.list.d/*.list
            echo -e "${GREEN}✓ Cleaned sources.list.d${NC}"
        fi
        
        echo ""
        echo -e "${BLUE}[*] Updating package lists...${NC}"
        apt update
        echo ""
        echo -e "${GREEN}✓ Repository baseline applied!${NC}"
        ;;
    4)
        backup_current
        clean_suspicious_repos
        ;;
    5)
        echo ""
        echo -e "${BLUE}========================================"
        echo "  RECOMMENDED GPG KEY SETUP"
        echo "========================================${NC}"
        echo ""
        echo "Modern Ubuntu/Mint systems use signed-by in source entries."
        echo ""
        echo "Official keys should be in:"
        echo "  /usr/share/keyrings/  (system keys)"
        echo "  /etc/apt/trusted.gpg.d/  (legacy format)"
        echo ""
        echo "Safe baseline GPG keys for Ubuntu:"
        echo "  - ubuntu-keyring package provides official keys"
        echo "  - Keys in /usr/share/keyrings/ubuntu-archive-keyring.gpg"
        echo ""
        echo "Safe baseline GPG keys for Linux Mint:"
        echo "  - linuxmint-keyring package provides official keys"
        echo "  - Keys in /usr/share/keyrings/linuxmint-keyring.gpg"
        echo ""
        echo "To verify official keyrings are installed:"
        echo "  Ubuntu: dpkg -l | grep ubuntu-keyring"
        echo "  Mint: dpkg -l | grep linuxmint-keyring"
        echo ""
        echo "To remove untrusted keys from trusted.gpg.d:"
        echo "  sudo rm /etc/apt/trusted.gpg.d/untrusted-key.gpg"
        echo ""
        echo "IMPORTANT: Never add keys from untrusted sources!"
        echo ""
        ;;
    6)
        echo "Exiting..."
        exit 0
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac

echo ""
echo -e "${BLUE}========================================"
echo "  IMPORTANT NOTES"
echo "========================================${NC}"
echo ""
echo "✓ Backup saved to: $BACKUP_DIR"
echo ""
echo "After resetting repositories:"
echo "  1. Run: sudo apt update"
echo "  2. Run: sudo apt upgrade"
echo "  3. Reinstall any needed PPAs carefully"
echo ""
echo "Only add third-party repositories from trusted sources!"
echo ""
echo "To restore from backup:"
echo "  sudo cp $BACKUP_DIR/sources.list /etc/apt/sources.list"
echo "  sudo cp -r $BACKUP_DIR/sources.list.d/* /etc/apt/sources.list.d/"
echo ""
